RESUME_OPEN_STATUS = "RESUME_OPEN_STATUS"
RESUME_CLOSE_STATUS = "RESUME_CLOSE_STATUS"

RESUME_STATUSES = (
    (RESUME_OPEN_STATUS, "Open"),
    (RESUME_CLOSE_STATUS, "Close"),
)

GRADE_JUNIOR = "GRADE_JUNIOR"
GRADE_MIDDLE = "GRADE_MIDDLE"
GRADE_SENIOR = "GRADE_SENIOR"

GRADES = (
    (GRADE_JUNIOR, "Junior"),
    (GRADE_MIDDLE, "Middle"),
    (GRADE_SENIOR, "Senior"),
)
