# Generated by Django 4.2.1 on 2023-05-25 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESUME_OPEN_STATUS", "Open"),
                            ("RESUME_CLOSE_STATUS", "Close"),
                        ],
                        default="RESUME_CLOSE_STATUS",
                        max_length=32,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("GRADE_JUNIOR", "Junior"),
                            ("GRADE_MIDDLE", "Middle"),
                            ("GRADE_SENIOR", "Senior"),
                        ],
                        max_length=32,
                    ),
                ),
                ("specialty", models.TextField()),
                ("salary", models.IntegerField()),
                ("education", models.TextField()),
                ("experience", models.TextField()),
                ("portfolio", models.TextField()),
                ("title", models.CharField(max_length=64)),
                ("phone", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="ResumeOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="resumes.resume"
                    ),
                ),
            ],
            options={
                "unique_together": {("resume", "owner")},
            },
        ),
    ]
